(define (problem sussman)
        (:domain blocksworld)
        (:objects A B C D E)
        (:init (ontable A) (clear A)
               (ontable B) (clear B)
               (ontable C) (clear C)
               (ontable D) (clear D)
               (ontable E) (clear E) (handempty))
        (:goal (and (on A B) (on B C) (on C D) (on D E))))
